export const GAME_CONFIG = {
  CANVAS_WIDTH: 400,
  CANVAS_HEIGHT: 600,
  BIRD_SIZE: 34,
  GRAVITY: 0.5,
  JUMP_FORCE: -8,
  PIPE_WIDTH: 60,
  PIPE_GAP: 180,
  PIPE_SPEED: 3,
  MIN_PIPE_INTERVAL: 1500,
  MAX_PIPE_INTERVAL: 2500,
  PIPE_SPAWN_CHANCE: 0.02,
};

export const BIRD_START_X = 80;
export const BIRD_START_Y = 300;
export const PIPE_SPAWN_X = 400;
export const GROUND_HEIGHT = 80;
